services:
  db:
    image: postgres:latest
    network_mode: bridge
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:latest
    network_mode: bridge
    ports:
      - "6379:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"

volumes:
  pg_data:
